let foodProduct = [
  {
    productId: "P001",
    productName: "Pizza",
    productNameTH: "พิซซ่า",
    productPrice: 59,
    Category: "FastFood",
    CategoryTH: "อาหารจานด่วน",
    size: [
      { name: "small", price: 59 },
      { name: "medium", price: 99 },
      { name: "large", price: 199 },
    ],
    addon: [
      { addonitem: "cheese", price: 50 },
      { addonitem: "peperlonie", price: 20 },
    ],
    image_url:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P002",
    productName: "Padthai",
    productNameTH: "ผัดไทย",
    productPrice: 49,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [
      { name: "small", price: 49 },
      { name: "medium", price: 99 },
      { name: "large", price: 199 },
    ],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P003",
    productName: "Sushi",
    productNameTH: "ซูชิ",
    productPrice: 80,
    Category: "JapaneseFood",
    CategoryTH: "อาหารญี่ปุ่น",
    addon: [],
    size: [],
    image_url:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=400&fit=crop",
    Status: "Outofstock",
  },
  {
    productId: "P004",
    productName: "TomYumKung",
    productNameTH: "ต้มยำกุ้ง",
    productPrice: 89,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P005",
    productName: "KhaoPad",
    productNameTH: "ข้าวผัด",
    productPrice: 45,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P006",
    productName: "SomTum",
    productNameTH: "ส้มตำ",
    productPrice: 39,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1559847844-5315695dadae?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P007",
    productName: "PadKrapao",
    productNameTH: "ผัดกะเพรา",
    productPrice: 45,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P008",
    productName: "GaengKeowWan",
    productNameTH: "แกงเขียวหวาน",
    productPrice: 55,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P009",
    productName: "stek",
    productNameTH: "สเต็ก",
    productPrice: 30,
    Category: "FrenchFood",
    CategoryTH: "อาหารฝรั่ง",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P010",
    productName: "KhaoManGai",
    productNameTH: "ข้าวมันไก่",
    productPrice: 45,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://static.thairath.co.th/media/dFQROr7oWzulq5Fa6rpOetuLxWtDW4pGVxTIT2bhWuo8KUmcxGVIisEysxd9YsSVQ0b.jpg",
    Status: "Available",
  },
  {
    productId: "P011",
    productName: "BaMee",
    productNameTH: "บะหมี่หมูแดง",
    productPrice: 40,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P012",
    productName: "KhaoSoi",
    productNameTH: "ข้าวซอย",
    productPrice: 55,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://static.thairath.co.th/media/dFQROr7oWzulq5Fa5nRPZVuR3wMxSXPiJRqDCxTALfAI7MxBpaH470UYN43WmS2Cr3z.jpg",
    Status: "Available",
  },
  {
    productId: "P013",
    productName: "Roti",
    productNameTH: "โรตี",
    productPrice: 35,
    Category: "Dessert",
    CategoryTH: "ของหวาน",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P024",
    productName: "KhaoSoi",
    productNameTH: "หมูกรอบผัดพริกแกง",
    productPrice: 80,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url: "https://i.ytimg.com/vi/dBSJ32IaeNI/maxresdefault.jpg",
    Status: "Available",
  },
  {
    productId: "P014",
    productName: "TomYumKung",
    productNameTH: "ต้มยำกุ้งน้ำข้น",
    productPrice: 120,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P015",
    productName: "YumWoonsen",
    productNameTH: "ยำวุ้นเส้น",
    productPrice: 55,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P016",
    productName: "KaiJeow",
    productNameTH: "ไข่เจียวหมูสับ",
    productPrice: 35,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P017",
    productName: "SpringRoll",
    productNameTH: "เปาะเปี๊ยะทอด",
    productPrice: 40,
    Category: "ThaiFood",
    CategoryTH: "อาหารไทย",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P018",
    productName: "Hamburger",
    productNameTH: "แฮมเบอร์เกอร์",
    productPrice: 89,
    Category: "FastFood",
    CategoryTH: "อาหารจานด่วน",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P019",
    productName: "FrenchFries",
    productNameTH: "เฟรนช์ฟรายส์",
    productPrice: 49,
    Category: "FastFood",
    CategoryTH: "อาหารจานด่วน",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P020",
    productName: "Spaghetti",
    productNameTH: "สปาเก็ตตี้คาโบนาร่า",
    productPrice: 99,
    Category: "FastFood",
    CategoryTH: "อาหารจานด่วน",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P021",
    productName: "MangoStickyRice",
    productNameTH: "ข้าวเหนียวมะม่วง",
    productPrice: 65,
    Category: "Dessert",
    CategoryTH: "ของหวาน",
    size: [],
    addon: [],
    image_url:
      "https://img.wongnai.com/p/1968x0/2019/02/22/a90c2f24358f43b5ae1be9797c07969a.jpg",
    Status: "Available",
  },
  {
    productId: "P022",
    productName: "IceCream",
    productNameTH: "ไอศครีมรวมรส",
    productPrice: 45,
    Category: "Dessert",
    CategoryTH: "ของหวาน",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P023",
    productName: "Sashimi",
    productNameTH: "ซาซิมิรวม",
    productPrice: 150,
    Category: "JapaneseFood",
    CategoryTH: "อาหารญี่ปุ่น",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1553621042-f6e147245754?w=400&h=400&fit=crop",
    Status: "Available",
  },
];
