let foodProduct = [
  {
    productId: "P001",
    productName: "Pizza",
    productNameTH: "พิซซ่า",
    productPrice: 59,
    Category: "FastFood",
    size: [
      { name: "medium", price: 99 },
      { name: "large", price: 199 },
    ],
    addon: [
      { addonitem: "cheese", price: 50 },
      { addonitem: "peperlonie", price: 20 },
    ],
    image_url:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P002",
    productName: "Padthai",
    productNameTH: "ผัดไทย",
    productPrice: 49,
    Category: "ThaiFood",
    size: [
      { name: "medium", price: 99 },
      { name: "large", price: 199 },
    ],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P003",
    productName: "Sushi",
    productNameTH: "ซูชิ",
    productPrice: 80,
    Category: "JapaneseFood",
    addon: [],
    size: [],
    image_url:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=400&fit=crop",
    Status: "Outofstock",
  },
  {
    productId: "P004",
    productName: "TomYumKung",
    productNameTH: "ต้มยำกุ้ง",
    productPrice: 89,
    Category: "ThaiFood",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P005",
    productName: "KhaoPad",
    productNameTH: "ข้าวผัด",
    productPrice: 45,
    Category: "ThaiFood",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P006",
    productName: "SomTum",
    productNameTH: "ส้มตำ",
    productPrice: 39,
    Category: "ThaiFood",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1559847844-5315695dadae?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P007",
    productName: "PadKrapao",
    productNameTH: "ผัดกะเพรา",
    productPrice: 45,
    Category: "ThaiFood",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P008",
    productName: "GaengKeowWan",
    productNameTH: "แกงเขียวหวาน",
    productPrice: 55,
    Category: "ThaiFood",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P009",
    productName: "stek",
    productNameTH: "สเต็ก",
    productPrice: 30,
    Category: "ThaiFood",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P010",
    productName: "KhaoManGai",
    productNameTH: "ข้าวมันไก่",
    productPrice: 45,
    Category: "ThaiFood",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P011",
    productName: "BaMee",
    productNameTH: "บะหมี่หมูแดง",
    productPrice: 40,
    Category: "ThaiFood",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P012",
    productName: "KhaoSoi",
    productNameTH: "ข้าวซอย",
    productPrice: 55,
    Category: "ThaiFood",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=400&fit=crop",
    Status: "Available",
  },
  {
    productId: "P013",
    productName: "Roti",
    productNameTH: "โรตี",
    productPrice: 35,
    Category: "Dessert",
    size: [],
    addon: [],
    image_url:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=400&fit=crop",
    Status: "Available",
  },
];
